name: CI/CD Workflow

on:
  push:
    branches:
      - lab/yacine
  pull_request:
    branches:
      - lab/yacine

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --force

      - name: Run tests
        run: npm test

      - name: Run build
        run: npm run build

      - name: Deploy to Vercel
        run: npx vercel deploy --prod --token $VERCEL_TOKEN --confirm
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN_JEST }}